project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - about.qmd
    - projects.qmd
    - cv.qmd
    - projects/ada-parc.qmd
    - projects/mood-disorders.qmd
    - projects/wic.qmd
    - projects/medicaid-expansion.qmd
    - research-statement.qmd

website:
  title: "Colin Heeneman"
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: research-statement.qmd
        text: Research
      - href: cv.qmd
        text: CV
    right:
      - href: https://github.com/colin-heeneman
        text: GitHub
      - href: mailto:colinheen@outlook.com
        text: Email

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
