---
title: "About"
---

# *Why I'm Committed To This Work*

Empathy has always been a central force guiding my personal, academic, and professional life. For as long as I can remember, I've been deeply saddened and perplexed by the continuation of such egregious socioeconomic inequality. My mother had premonitions that justice-oriented work was on the horizon when I would do such things as saving half my sandwich for someone seeking donation at Union Station. But such acts felt less in the spirit of heroism than basic humility. It feels only fitting, now, to make that kid proud by dedicating my professional life to understanding and combating the structures which have given rise to our current reality, one in which we are poised to mint our first trillionaire before eliminating abject poverty.

However ironically, precisely because such a state of affairs is a policy choice rather than dystopian prophecy, there exists the hope of its amelioration. We must simply open our eyes, and summon our wits, our optimism, our courage, to steadfastly push for a more just society. A society which truly takes seriously its capacity to foster or destroy the conditions which give each individual the opportunity to flourish. My commitment to this worldview sharpened during my undergraduate studies in political science at the University of Illinois Urbana-Champaign. Here, was the genesis of my ability to link my innate compassion with the tools of rigorous analysis. Such an approach guided my advocacy as part of Active Minds, a student mental health organization for which I served as Co-President my senior year. A role of profound meaning, it deepened my understanding of public service and affirmed my will to to develop systems which minimize human suffering.

After graduating, I wanted to delve deeper into the policy world and expand my knowledge-base in systems which support the well-being of communities. Hence, the next two years in my academic journey were spent pursuing an MPP at The University of Illinois Chicago with a specialization in Public Health. During my coursework here, I developed an appreciation for the framework of upstream intervention. An empathic society makes great effort to prevent problems rather than just manage their symptoms. Another highlight of my graduate experience was the mentorship of Dr. Allyson Holbrook, under whom I completed an independent study using National Health Interview Survey (NHIS) data to explore mental health outcomes. More than a project of quantitative analysis, it was a chance to examine how structural factors and the social determinants of health influence well-being at an individual and communal level.

Another domain in which I've grown professionally and technically is at the Voorhees Center for Neighborhood and Community Improvement. While here, my main project has been development of the ADA-PARC website, a resource for the disability community and advocates that hosts raw data and analysis related to quality of life outcomes within the disabled community. Strengthening my technical foundation in statistical software and applied data visualization, this work has also brought me closer to a community which experiences severe inequities.

We have, collectively, chosen greed over empathy. No choice poisons the well of humanity more deeply. For such extreme inequality not only plunders the spirit of those who face capitalistic-condemnation, it creates a class-chasm that eventually, rips us apart. What we need is a renewal. Of our social contract, yes, but also of our commitment to building systems which realize the human right to self-actualization. My continued exploration of the interface between built socioeconomic environments and individual human development, reflected in the projects throughout this portfolio, is oriented towards expanding our understanding of the pathways to such a society.
